name: lucide_flutter
description: A Flutter package for Lucide icons.
version: 1.2.0
repository: https://github.com/cliq-terminal/lucide

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: LucideIcons
      fonts:
        - asset: assets/lucide.ttf
