name: lucide_flutter
description: A Flutter package providing Lucide icons.
version: 0.540.0
repository: https://github.com/cliq-terminal/lucide_flutter
issue_tracker: https://github.com/cliq-terminal/lucide_flutter/issues
topics:
  - lucide
  - icons
  - flutter

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: LucideIcons
      fonts:
        - asset: assets/lucide.ttf
